use liga; 
SELECT * FROM Partido  WHERE MONTH(fecha) = 2;
SELECT UPPER(CONCAT(Nombre, ' ', Apellido)) AS "Nombre Completo" FROM Jugador;
SELECT Web FROM Equipo WHERE Web NOT LIKE '%www%';
SELECT * FROM Equipo WHERE Web LIKE '%basket%';
SELECT REPLACE(Web, 'http://', '') AS WebSinHTTP FROM Equipo;
SELECT 'El jugador con nombre y apellidos: Juan Carlos Navarro juega en la posición: escolta' AS FraseResultado;
SELECT * FROM Equipo WHERE LENGTH(Nombre) <= 12;
SELECT * FROM Jugador WHERE YEAR(fecha_alta) IN (2008, 2011);
SELECT REPLACE(Web, 'http://', 'https://') AS WebSegura FROM Equipo;
SELECT Nombre, REVERSE(Nombre) AS NombreInvertido FROM Jugador;
SELECT LPAD(Nombre, 20, '*') AS Nombre FROM Equipo;
SELECT Apellido, SUBSTRING(Apellido, 1, 3) AS TresPrimerasLetras FROM Jugador;
SELECT Nombre, LOCATE('a', Nombre) AS Posicion_LetraA FROM Equipo;
SELECT Nombre, Apellido, CASE WHEN YEAR(Fecha_Alta) < 2010 THEN 'Veterano'ELSE 'Moderno'END AS CategoriaJugador FROM Jugador;
SELECT * FROM Jugador WHERE Apellido LIKE '%ez';
SELECT Nombre FROM Equipo ORDER BY LENGTH(Nombre);
SELECT LOWER(Nombre) AS NombreMinusculas FROM Jugador;
SELECT Nombre, LEFT(Apellido, 2) AS DosPrimerasApellido FROM Jugador;
SELECT Nombre, YEAR(Fecha_Alta) AS AnioAlta FROM Jugador;
SELECT CONCAT_WS('-', Nombre, Apellido) AS NombreYApellido FROM Jugador;